version: '3'

networks: 
  php-network:
    driver: bridge

services:

  php:
    build: 
      dockerfile: ./Dockerfile
      context: .
    #mapeando para localhost:8080
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    networks:
      - php-network
    depends_on: 
      - db-php
    #conecta ao containers do banco pela url http://database
    links:
      - "db-php:database"

  db-php:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes:
      - ./banco:/var/lib/mysql
    networks:
      - php-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
